import { useState, useEffect } from 'react';

// ── Utility helpers ───────────────────────────────────────────────────────────

export function formatDetectionTimestamp(detection) {
  return detection?.timestamp
    ? new Date(detection.timestamp).toLocaleString()
    : detection?.detected || new Date().toLocaleString();
}

export function getEvidenceReportData(detection, asset) {
  const generatedAt = new Date().toLocaleString();
  const observedAt = formatDetectionTimestamp(detection);
  const evidenceText = Array.isArray(detection?.evidence)
    ? detection.evidence.filter(Boolean)
    : detection?.evidence
      ? [detection.evidence]
      : [];
  const transformations = Array.isArray(detection?.transformations)
    ? detection.transformations.filter(Boolean)
    : detection?.transformations
      ? [detection.transformations]
      : detection?.mod
        ? [detection.mod]
        : [];

  return {
    generatedAt,
    observedAt,
    detectionId: detection?.id || 'pending-review',
    status: (detection?.type || 'review').toUpperCase(),
    verdict: detection?.geminiVerdict || 'UNKNOWN',
    confidence: detection?.confidence ?? 0,
    phashSimilarity: detection?.phashSim ?? 0,
    title: asset?.title || 'Unknown asset',
    owner: asset?.owner || 'Unknown owner',
    sport: asset?.sport || 'Unknown sport',
    license: asset?.license || 'Unspecified',
    fingerprint: asset?.phash || 'Unavailable',
    frameRef: asset?.frame || 'N/A',
    suspectUrl: detection?.url || 'Unavailable',
    modificationNotes: detection?.mod || 'None recorded',
    reasoning: detection?.reasoning || 'No narrative reasoning captured in this session.',
    evidence: evidenceText.length ? evidenceText : ['No structured evidence captured.'],
    transformations: transformations.length ? transformations : ['Not specified'],
  };
}

export function buildEvidenceReport(detection, asset) {
  const report = getEvidenceReportData(detection, asset);
  const lines = [
    'SPORTSGUARD AI',
    'DIGITAL MEDIA EVIDENCE REPORT',
    'Prepared for rights enforcement and internal review',
    '',
    `Generated: ${report.generatedAt}`,
    `Detection ID: ${report.detectionId}`,
    `Case Status: ${report.status}`,
    `Verdict: ${report.verdict}`,
    `Confidence Score: ${report.confidence}%`,
    `pHash Similarity: ${report.phashSimilarity}%`,
    `Observed: ${report.observedAt}`,
    '',
    '1. PROTECTED ASSET',
    `Title: ${report.title}`,
    `Owner: ${report.owner}`,
    `Sport: ${report.sport}`,
    `License: ${report.license}`,
    `Fingerprint: ${report.fingerprint}`,
    `Frame Reference: ${report.frameRef}`,
    '',
    '2. SUSPECT SOURCE',
    `URL: ${report.suspectUrl}`,
    `Modification Notes: ${report.modificationNotes}`,
    '',
    '3. AI FINDINGS',
    `Reasoning: ${report.reasoning}`,
    `Evidence Points: ${report.evidence.join('; ')}`,
    `Observed Transformations: ${report.transformations.join(', ')}`,
    '',
    '4. CHAIN OF REVIEW',
    'This report was generated by SportsGuard AI for evidentiary review, export, and takedown preparation.',
  ];
  return lines.join('\n');
}

export function buildEvidenceReportHtml(detection, asset) {
  const report = getEvidenceReportData(detection, asset);
  const evidenceItems = report.evidence.map(item => `<li>${item}</li>`).join('');
  const transformationItems = report.transformations.map(item => `<li>${item}</li>`).join('');
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>SportsGuard Evidence Report</title>
  <style>
    body { margin: 0; padding: 32px; background: #eef2f7; color: #0b1220; font: 14px/1.55 Inter, Arial, sans-serif; }
    .report { max-width: 920px; margin: 0 auto; background: #ffffff; border: 1px solid rgba(11,18,32,0.08); border-radius: 20px; overflow: hidden; box-shadow: 0 18px 50px rgba(11,18,32,0.12); }
    .hero { padding: 28px 32px 24px; background: linear-gradient(135deg, #0b1220 0%, #15203a 62%, #16a34a 140%); color: #ffffff; }
    .kicker { font: 600 11px/1.4 'JetBrains Mono', monospace; letter-spacing: 0.22em; text-transform: uppercase; color: #8ff0b2; }
    .title { margin: 12px 0 8px; font: 800 34px/1.05 Outfit, Arial, sans-serif; letter-spacing: -0.03em; }
    .sub { margin: 0; color: rgba(255,255,255,0.84); }
    .meta { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 14px; padding: 22px 32px; background: #f8fafc; border-bottom: 1px solid rgba(11,18,32,0.08); }
    .meta-card, .section { background: #ffffff; border: 1px solid rgba(11,18,32,0.08); border-radius: 16px; padding: 16px 18px; }
    .label { font: 600 10px/1.4 'JetBrains Mono', monospace; letter-spacing: 0.16em; text-transform: uppercase; color: #7b8497; }
    .value { margin-top: 8px; font-weight: 700; font-size: 22px; }
    .body { padding: 24px 32px 32px; }
    .grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 18px; }
    .section-title { margin: 0 0 14px; font: 700 16px/1.2 Outfit, Arial, sans-serif; text-transform: uppercase; letter-spacing: 0.04em; }
    .row { display: flex; justify-content: space-between; gap: 16px; padding: 9px 0; border-bottom: 1px solid rgba(11,18,32,0.06); }
    .row:last-child { border-bottom: 0; }
    .row span:first-child { color: #64748b; font-weight: 500; }
    .row span:last-child { text-align: right; font-weight: 600; }
    .full { margin-top: 18px; }
    ul { margin: 10px 0 0 18px; padding: 0; }
    li + li { margin-top: 6px; }
    .footer { margin-top: 18px; padding-top: 18px; border-top: 1px solid rgba(11,18,32,0.08); color: #64748b; font-size: 12px; }
  </style>
</head>
<body>
  <article class="report">
    <header class="hero">
      <div class="kicker">SportsGuard AI · Rights Protection Suite</div>
      <h1 class="title">Digital Media Evidence Report</h1>
      <p class="sub">Prepared for enforcement review, provenance tracking, and takedown support.</p>
    </header>
    <section class="meta">
      <div class="meta-card">
        <div class="label">Verdict</div>
        <div class="value">${report.verdict.replaceAll('_', ' ')}</div>
      </div>
      <div class="meta-card">
        <div class="label">Confidence</div>
        <div class="value">${report.confidence}%</div>
      </div>
      <div class="meta-card">
        <div class="label">pHash Similarity</div>
        <div class="value">${report.phashSimilarity}%</div>
      </div>
    </section>
    <section class="body">
      <div class="grid">
        <div class="section">
          <h2 class="section-title">Case Summary</h2>
          <div class="row"><span>Detection ID</span><span>${report.detectionId}</span></div>
          <div class="row"><span>Case Status</span><span>${report.status}</span></div>
          <div class="row"><span>Generated</span><span>${report.generatedAt}</span></div>
          <div class="row"><span>Observed</span><span>${report.observedAt}</span></div>
        </div>
        <div class="section">
          <h2 class="section-title">Protected Asset</h2>
          <div class="row"><span>Title</span><span>${report.title}</span></div>
          <div class="row"><span>Rights Holder</span><span>${report.owner}</span></div>
          <div class="row"><span>License</span><span>${report.license}</span></div>
          <div class="row"><span>Frame Reference</span><span>${report.frameRef}</span></div>
        </div>
      </div>
      <div class="grid full">
        <div class="section">
          <h2 class="section-title">Suspect Source</h2>
          <div class="row"><span>URL</span><span>${report.suspectUrl}</span></div>
          <div class="row"><span>Modification Notes</span><span>${report.modificationNotes}</span></div>
          <div class="row"><span>Fingerprint</span><span>${report.fingerprint}</span></div>
          <div class="row"><span>Sport</span><span>${report.sport}</span></div>
        </div>
        <div class="section">
          <h2 class="section-title">AI Findings</h2>
          <div><strong>Reasoning</strong><div style="margin-top: 8px; color: #334155;">${report.reasoning}</div></div>
          <div style="margin-top: 14px;"><strong>Evidence Points</strong><ul>${evidenceItems}</ul></div>
          <div style="margin-top: 14px;"><strong>Observed Transformations</strong><ul>${transformationItems}</ul></div>
        </div>
      </div>
      <div class="footer">
        SportsGuard AI generated this document for internal review and rights-enforcement workflows. Retain alongside original asset registration and source capture logs.
      </div>
    </section>
  </article>
</body>
</html>`;
}

export function buildDmcaNotice(detection, asset) {
  const owner = asset?.owner || 'Authorized rights holder';
  const title = asset?.title || 'Protected sports media asset';
  const url = detection?.url || 'Unavailable URL';
  const confidence = detection?.confidence ?? 0;
  const evidence = Array.isArray(detection?.evidence) ? detection.evidence.join('; ') : detection?.evidence || detection?.reasoning || 'AI matching evidence available upon request.';
  const fingerprint = asset?.phash || 'Unavailable';
  return [
    'Subject: DMCA Takedown Notice - Unauthorized Sports Media Use',
    '',
    'To whom it may concern,',
    '',
    `I am submitting this notice on behalf of ${owner}, the rights holder for the protected asset "${title}".`,
    '',
    'We have identified material appearing at the following location that is believed to infringe our copyrighted sports media:',
    url,
    '',
    'SportsGuard AI analysis indicates that this content is an unauthorized copy or derivative of our protected material.',
    `Confidence score: ${confidence}%`,
    `Reference fingerprint: ${fingerprint}`,
    `Supporting evidence: ${evidence}`,
    '',
    'We request that you remove or disable access to this material promptly in accordance with applicable copyright law.',
    '',
    'I have a good-faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law.',
    'The information in this notice is accurate, and under penalty of perjury, I am authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.',
    '',
    `Rights Holder: ${owner}`,
    `Protected Asset: ${title}`,
    `Generated: ${new Date().toLocaleString()}`,
    '',
    'Sincerely,',
    owner,
  ].join('\n');
}

export function buildVerificationCertificate(asset) {
  return [
    'SPORTSGUARD VERIFIED ASSET CERTIFICATE',
    `Issued: ${new Date().toLocaleString()}`,
    '',
    `Asset ID: ${asset?.id || 'Pending'}`,
    `Title: ${asset?.title || 'Untitled asset'}`,
    `Rights Holder: ${asset?.owner || 'Unknown owner'}`,
    `Sport: ${asset?.sport || 'Unknown sport'}`,
    `License: ${asset?.license || 'Unspecified'}`,
    `Registered On: ${asset?.registered ? new Date(asset.registered).toLocaleString() : 'Unknown date'}`,
    `Fingerprint: ${asset?.phash || 'Unavailable'}`,
    `Frame Reference: ${asset?.frame || 'N/A'}`,
    '',
    'Verification Status: ACTIVE',
    'Badge: VERIFIED BY SPORTSGUARD AI',
    '',
    'This certificate confirms that the asset has been registered and fingerprinted in the SportsGuard protection registry.',
  ].join('\n');
}

export async function copyTextToClipboard(text) {
  if (navigator.clipboard?.writeText) {
    await navigator.clipboard.writeText(text);
    return;
  }
  const area = document.createElement('textarea');
  area.value = text;
  area.setAttribute('readonly', '');
  area.style.position = 'absolute';
  area.style.left = '-9999px';
  document.body.appendChild(area);
  area.select();
  document.execCommand('copy');
  document.body.removeChild(area);
}

export function downloadTextFile(filename, contents) {
  const blob = new Blob([contents], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function downloadHtmlFile(filename, contents) {
  const blob = new Blob([contents], { type: 'text/html;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function EvidenceReportDocument({ detection, asset }) {
  const report = getEvidenceReportData(detection, asset);
  const verdictTone = detection?.type === 'piracy' ? 'coral' : detection?.type === 'clean' ? 'moss' : 'butter';

  return (
    <div className="evidence-doc">
      <div className="evidence-doc__hero">
        <div className="evidence-doc__letterhead">
          <div className="evidence-doc__brand">SPORTSGUARD AI</div>
          <div className="evidence-doc__kicker">Digital Media Protection Division</div>
        </div>
        <div className="evidence-doc__titleWrap">
          <div className="evidence-doc__title">Evidence Report</div>
          <div className="evidence-doc__subtitle">Prepared for enforcement review, provenance tracking, and takedown support.</div>
        </div>
        <div className="evidence-doc__seal">Filed</div>
      </div>

      <div className="evidence-doc__summary">
        <div className="evidence-doc__metric">
          <span className="evidence-doc__label">Verdict</span>
          <strong className={`evidence-doc__value tone-${verdictTone}`}>{report.verdict.replaceAll('_', ' ')}</strong>
        </div>
        <div className="evidence-doc__metric">
          <span className="evidence-doc__label">Confidence</span>
          <strong className="evidence-doc__value">{report.confidence}%</strong>
        </div>
        <div className="evidence-doc__metric">
          <span className="evidence-doc__label">pHash Similarity</span>
          <strong className="evidence-doc__value">{report.phashSimilarity}%</strong>
        </div>
      </div>

      <div className="evidence-doc__body">
        <div className="evidence-doc__grid">
          <section className="evidence-doc__section">
            <h4>Case Summary</h4>
            <div className="evidence-doc__rows">
              <div className="evidence-doc__row"><span>Detection ID</span><strong>{report.detectionId}</strong></div>
              <div className="evidence-doc__row"><span>Case Status</span><strong>{report.status}</strong></div>
              <div className="evidence-doc__row"><span>Generated</span><strong>{report.generatedAt}</strong></div>
              <div className="evidence-doc__row"><span>Observed</span><strong>{report.observedAt}</strong></div>
            </div>
          </section>

          <section className="evidence-doc__section">
            <h4>Protected Asset</h4>
            <div className="evidence-doc__rows">
              <div className="evidence-doc__row"><span>Title</span><strong>{report.title}</strong></div>
              <div className="evidence-doc__row"><span>Rights Holder</span><strong>{report.owner}</strong></div>
              <div className="evidence-doc__row"><span>License</span><strong>{report.license}</strong></div>
              <div className="evidence-doc__row"><span>Frame Reference</span><strong>{report.frameRef}</strong></div>
            </div>
          </section>
        </div>

        <div className="evidence-doc__grid evidence-doc__grid--stack">
          <section className="evidence-doc__section">
            <h4>Suspect Source</h4>
            <div className="evidence-doc__rows">
              <div className="evidence-doc__row evidence-doc__row--top"><span>URL</span><strong className="evidence-doc__wrap">{report.suspectUrl}</strong></div>
              <div className="evidence-doc__row"><span>Modification Notes</span><strong>{report.modificationNotes}</strong></div>
              <div className="evidence-doc__row"><span>Fingerprint</span><strong>{report.fingerprint}</strong></div>
              <div className="evidence-doc__row"><span>Sport</span><strong>{report.sport}</strong></div>
            </div>
          </section>

          <section className="evidence-doc__section">
            <h4>AI Findings</h4>
            <div className="evidence-doc__textBlock">
              <span className="evidence-doc__label">Reasoning</span>
              <p>{report.reasoning}</p>
            </div>
            <div className="evidence-doc__listWrap">
              <span className="evidence-doc__label">Evidence Points</span>
              <ul>{report.evidence.map((item, idx) => <li key={`ev-${idx}`}>{item}</li>)}</ul>
            </div>
            <div className="evidence-doc__listWrap">
              <span className="evidence-doc__label">Observed Transformations</span>
              <ul>{report.transformations.map((item, idx) => <li key={`tr-${idx}`}>{item}</li>)}</ul>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
}

// ── UI Components ─────────────────────────────────────────────────────────────

export function Counter({ to, duration = 1100, suffix = '', prefix = '', decimals = 0 }) {
  const [v, setV] = useState(0);
  useEffect(() => {
    let raf, start;
    const step = (ts) => {
      if (!start) start = ts;
      const p = Math.min(1, (ts - start) / duration);
      const eased = 1 - Math.pow(1 - p, 3);
      setV(to * eased);
      if (p < 1) raf = requestAnimationFrame(step);
    };
    raf = requestAnimationFrame(step);
    return () => cancelAnimationFrame(raf);
  }, [to, duration]);
  return <span>{prefix}{decimals ? v.toFixed(decimals) : Math.round(v).toLocaleString()}{suffix}</span>;
}

export function Sparkline({ values = [3,5,4,7,6,9,8,11,10,13,12,15], w = 64, h = 24, color = 'var(--pine)' }) {
  const max = Math.max(...values), min = Math.min(...values);
  const range = max - min || 1;
  const pts = values.map((v, i) => {
    const x = (i / (values.length - 1)) * w;
    const y = h - ((v - min) / range) * (h - 4) - 2;
    return `${x.toFixed(1)},${y.toFixed(1)}`;
  }).join(' ');
  return (
    <svg width={w} height={h} viewBox={`0 0 ${w} ${h}`} className="stat-spark">
      <polyline points={pts} fill="none" stroke={color} strokeWidth="1.5" strokeLinejoin="round" strokeLinecap="round" />
    </svg>
  );
}

export function ConfBar({ value }) {
  const color = value >= 85 ? 'var(--coral)' : value >= 70 ? 'var(--butter)' : value >= 30 ? 'var(--ink-mute)' : 'var(--moss)';
  return (
    <div className="conf-row">
      <div className="conf-track">
        <div className="conf-fill" style={{ width: `${value}%`, background: color }}/>
      </div>
      <span className="conf-num">{value}</span>
    </div>
  );
}

export function Placeholder({ tone = 'pine', label = 'CRICKET', frame = 'F-00:00:00', live = false }) {
  const toneClasses = {
    pine: 'ph ph-pine ph-stripes',
    coral: 'ph ph-coral ph-dots',
    cream: 'ph ph-cream ph-dots',
    grid: 'ph ph-grid',
    dots: 'ph ph-dots',
    stripes: 'ph ph-stripes',
  };
  const cls = toneClasses[tone] || toneClasses.pine;
  return (
    <div className={cls}>
      <span className="ph-corner tl"/><span className="ph-corner tr"/>
      <span className="ph-corner bl"/><span className="ph-corner br"/>
      <span className="ph-cap">{label} · {frame}</span>
      {live && <span className="ph-rec">REC</span>}
    </div>
  );
}

export function ConfDial({ value = 0, type = 'piracy', size = 180 }) {
  const [v, setV] = useState(0);
  useEffect(() => { const t = setTimeout(() => setV(value), 100); return () => clearTimeout(t); }, [value]);
  const r = size * 0.4, cx = size/2, cy = size/2;
  const c = 2 * Math.PI * r;
  const off = c - (v / 100) * c;
  const colors = {
    piracy: { ring: 'var(--coral)',  track: 'rgba(255,107,71,0.15)' },
    review: { ring: 'var(--butter)', track: 'rgba(245,201,91,0.2)' },
    clean:  { ring: 'var(--moss)',   track: 'rgba(91,166,119,0.18)' },
  };
  const col = colors[type] || colors.piracy;
  const fontSize = size * 0.28;
  return (
    <div style={{ position: 'relative', width: size, height: size }}>
      <svg width={size} height={size} viewBox={`0 0 ${size} ${size}`}>
        <circle cx={cx} cy={cy} r={r} fill="none" stroke={col.track} strokeWidth={size * 0.06}/>
        <circle cx={cx} cy={cy} r={r} fill="none" stroke={col.ring} strokeWidth={size * 0.06}
          strokeDasharray={c} strokeDashoffset={off} strokeLinecap="round"
          transform={`rotate(-90 ${cx} ${cy})`}
          style={{ transition: 'stroke-dashoffset 1.1s cubic-bezier(0.2, 0.7, 0.1, 1)' }}/>
      </svg>
      <div style={{
        position: 'absolute', inset: 0, display: 'grid', placeItems: 'center',
        fontFamily: 'Fraunces, serif', fontVariationSettings: "'opsz' 144, 'SOFT' 50",
        fontSize, lineHeight: 1, fontWeight: 400, letterSpacing: '-0.03em', color: 'currentColor'
      }}>
        {Math.round(v)}<span style={{ fontSize: fontSize * 0.45, opacity: 0.7 }}>%</span>
      </div>
    </div>
  );
}

export const Icon = {
  shield: <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3l8 3v6c0 5-3.5 8-8 9-4.5-1-8-4-8-9V6l8-3z"/><path d="M9 12l2 2 4-4"/></svg>,
  upload: <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M12 16V4"/><path d="M6 10l6-6 6 6"/><rect x="3" y="18" width="18" height="3" rx="1"/></svg>,
  link:   <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M10 14a4 4 0 0 0 5.66 0l3-3a4 4 0 1 0-5.66-5.66l-1.5 1.5"/><path d="M14 10a4 4 0 0 0-5.66 0l-3 3a4 4 0 1 0 5.66 5.66l1.5-1.5"/></svg>,
  grid:   <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinejoin="round"><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></svg>,
  scan:   <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M3 7V5a2 2 0 0 1 2-2h2"/><path d="M17 3h2a2 2 0 0 1 2 2v2"/><path d="M21 17v2a2 2 0 0 1-2 2h-2"/><path d="M7 21H5a2 2 0 0 1-2-2v-2"/><path d="M7 12h10"/></svg>,
  search: <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><circle cx="11" cy="11" r="7"/><path d="M21 21l-4.3-4.3"/></svg>,
  arrow:  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="arrow"><path d="M5 12h14"/><path d="M13 5l7 7-7 7"/></svg>,
  close:  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"><path d="M6 6l12 12M18 6L6 18"/></svg>,
  check:  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round"><path d="M5 12l5 5L20 7"/></svg>,
  bolt:   <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor"><path d="M13 2L4 14h7l-1 8 9-12h-7l1-8z"/></svg>,
  home:   <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M3 11l9-8 9 8v9a2 2 0 0 1-2 2h-4v-7h-6v7H5a2 2 0 0 1-2-2v-9z"/></svg>,
  fingerprint: <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><path d="M6 11a6 6 0 0 1 12 0v3a4 4 0 0 0 .5 2"/><path d="M9 11a3 3 0 0 1 6 0v4a3 3 0 0 0 .5 1.6"/><path d="M12 11v5a2 2 0 0 0 .3 1.1"/><path d="M5 14a8 8 0 0 0 1 4"/><path d="M19 21a10 10 0 0 0 1-7"/></svg>,
  doc: <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6"/><path d="M16 13H8"/><path d="M16 17H8"/><path d="M10 9H8"/></svg>,
  copy: <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><rect x="9" y="9" width="13" height="13" rx="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg>,
  info: <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><path d="M12 16v-4M12 8h.01"/></svg>,
};
